name: Deploy
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    # Allow GITHUB_TOKEN to write deployments for my action (https://docs.github.com/en/actions/security-guides/automatic-token-authentication)
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Await CF Pages
        uses: WalshyDev/cf-pages-await@v1
        with:
          # Use an API token (Recommended!)
          apiToken: ${{ secrets.CF_API_TOKEN }}

          accountId: '9793bc27d30f5d738baf5e5a491b7416'
          project: 'nuvla-ui'
          # Add this if you want GitHub Deployments (see below)
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          # Add this if you want to wait for a deployment triggered by a specfied commit
          commitHash: ${{ steps.push-changes.outputs.commit-hash }}
